# Pandas

- Pandas is library  of python.    
- It was created in 2008 by Wes McKinney.   
- It is used for working with data set.   
- It is used for cleaning, analyzing, exploring, and manipulating data.   
- It perform operation on structured data.  
- Data structure in python : Series, DataFrame 
- loc[] - label based 
- iloc[] - index based

## Series

- Series is one-dimensional labeled array capable of holding any data type.
- Series has index(labeled).
- It Stores homogeneous or heterogeneous data.
- Size is dynamic.
- Built on NumPy array.
- Series has two main part : 
1. value - actual data
2. index - labels for data

### Series from list

In [ ]:
import pandas as pd

data = [1,2,3] #data with same data type 
data1 = ["Sayma" , 96.20 , 50] #data with difference data type 
seri = pd.Series(data)
seri1 = pd.Series(data1)
print(seri)
print(seri1)

0    1
1    2
2    3
dtype: int64
0    Sayma
1     96.2
2       50
dtype: object

### Series with custom index

In [10]:
import pandas as pd 

marks = pd.Series([96.20 , 96 , 90] , index=["Arish" , "Sayma" , "Supriya"])
print(marks)

Arish      96.2
Sayma      96.0
Supriya    90.0
dtype: float64

### Series from dictionary

In [10]:
import pandas as pd 

data = {"Sayma" : 96 , "Mahek" : 97 , "Ram" : 90}
S = pd.Series(data)
print(S)

Sayma    96
Mahek    97
Ram      90
dtype: int64

### Dictionary with Custom index 

if index is given but value is not assigned to it then it will print NaN.

In [13]:
import pandas as pd 

row_data = {"English" : "Yes" , "Math" : "No" , "Physics" : "Yes"}
data = pd.Series(row_data , index=["English", "Math", "History"])
print(data)

English    Yes
Math        No
History    NaN
dtype: str

### Accessing series data

In [14]:
import pandas as pd 

data = pd.Series([87,90,15] , index = ["T-shirts","Pants","blazer"])
data1 = pd.Series(["Sayma",90,18.45])
print(data)
print(data["T-shirts"]) # accessing through labeled index 
print(data1[2]) # accessing data through index

T-shirts    87
Pants       90
blazer      15
dtype: int64
87
18.45

### Series operations 
- .sum() - sumation of all elements 
- .mean() - average of elements 
- .min() - returns minimum value present in the list 
- .max() - returns maximum value present in the list

In [15]:
import pandas as pd 

data = [34,76,59,53,90,53,26,84,24,16,78,46,88,12]
do = pd.Series(data)
print(do.sum())
print(do.mean())
print(do.min())
print(do.max())

739
52.785714285714285
12
90

## Dataframe

- Dataframe is two-dimensional label array.
- dataframe is size mutable .
- dataframe contains rows and columns.
- dataframe is in tabular format.
- dataframe cata store different data type 
- DataFrame contains :
1. Rows(index)
2. Columns
3. Data values

### List of Lists

In [31]:
import pandas as pd 

data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

df = pd.DataFrame(data)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### List of Tuples

In [41]:
import pandas as pd 

data = [("Sayma", 20),
        ("Ayesha", 21),
        ("Fatima", 19)]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

     Name  Age
0   Sayma   20
1  Ayesha   21
2  Fatima   19

### data frames with dictionary

In [42]:
import pandas as pd 

data = {
    "Name" : ["millle","will","bob"],
    "Age" : [18,19,15],
    "Marks" : [99,87.99,90]
}

df = pd.DataFrame(data)
print(df)

     Name  Age  Marks
0  millle   18  99.00
1    will   19  87.99
2     bob   15  90.00

### data frame with list of list

In [43]:
import pandas as pd 

data = pd.DataFrame([["Who are you?","what's up?","how are you?"],["I'm sayma","hey, hello","I'm good"]], columns=["Q1","Q2","Q3"])
print(data)

             Q1          Q2            Q3
0  Who are you?  what's up?  how are you?
1     I'm sayma  hey, hello      I'm good

### Accessing dataframe

In [46]:
import pandas as pd 

data = {
    "Name" : ["millle","will","bob"],
    "Age" : [18,19,15],
    "Marks" : [99,87.99,90]
}

df = pd.DataFrame(data)
print(df)
print(df["Name"])
print("\n")
print(df.loc[2])
print("\n")
print(df.iloc[1])

     Name  Age  Marks
0  millle   18  99.00
1    will   19  87.99
2     bob   15  90.00
0    millle
1      will
2       bob
Name: Name, dtype: str


Name      bob
Age        15
Marks    90.0
Name: 2, dtype: object


Name      will
Age         19
Marks    87.99
Name: 1, dtype: object

### DataFrame operations 

- .head(int) - it returns first rows (by default - 5)
- .tail(int) - it returns last rowws (by default - 5)
- .shape - returns number of rows and columns 
- .info() - returns information related to the dataframe 
- .describe() - returns statistical information of dataframe 
- .sample() - returns random row

In [55]:
import pandas as pd 

data = {
    "Name" : ["millle","will","bob","ram","laila","arjun","zaid","nisha"],
    "Age" : [18,19,15,43,11,67,51,28],
    "Marks" : [99,87.99,90,95,67.77,56,88,67]
}

df = pd.DataFrame(data)
#print(df)
#print("\n")
print(df.head(2))
print("\n")
print(df.tail(2))
print("\n")
print(df.shape)
print("\n")
print(df.info())
print("\n")
print(df.describe())
print("\n")
print(df.sample())

     Name  Age  Marks
0  millle   18  99.00
1    will   19  87.99


    Name  Age  Marks
6   zaid   51   88.0
7  nisha   28   67.0


(8, 3)


<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Age     8 non-null      int64
 2   Marks   8 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 324.0 bytes
None


             Age      Marks
count   8.000000   8.000000
mean   31.500000  81.345000
std    20.057061  15.556077
min    11.000000  56.000000
25%    17.250000  67.577500
50%    23.500000  87.995000
75%    45.000000  91.250000
max    67.000000  99.000000


   Name  Age  Marks
1  will   19  87.99

### Creating DataFrame From a NumPy Array

In [56]:
import numpy as np

arr = np.array([[100, 200],
                [300, 400],
                [500, 600]])

df = pd.DataFrame(arr, columns=["Marks1", "Marks2"])
print(df)

   Marks1  Marks2
0     100     200
1     300     400
2     500     600

## Column Selection

In [57]:
import pandas as pd

data = {
    "name" : ["Sayma","Arish","Fatima","ayesha"],
    "age" : [18,40,22,42]
}

df = pd.DataFrame(data)

#check columns
print("\n") 
print(df.columns)

#using square bracket
print("\n")
print(df["name"]) 

# using dot(.) operator (only if column name have not space)
print("\n")
print(df.age)

#using loc[]
# : - means all rows 
print("\n")
print(df.loc[: , "age"]) 

#multiple columns with loc
print("\n") 
print(df.loc[:,["name" , "age"]])

Index(['name', 'age'], dtype='str')


0     Sayma
1     Arish
2    Fatima
3    ayesha
Name: name, dtype: str


0    18
1    40
2    22
3    42
Name: age, dtype: int64


0    18
1    40
2    22
3    42
Name: age, dtype: int64


     name  age
0   Sayma   18
1   Arish   40
2  Fatima   22
3  ayesha   42

## Row selection

In [68]:
import pandas as pd

data = {
    "name" : ["Sayma","Arish","Fatima","ayesha"],
    "age" : [18,40,22,42]
}

df = pd.DataFrame(data)

#single row
print(df.loc[0])

#multiple rows
print("\n")
print(df.loc[[0,2]])

#slicing 
print("\n")
print(df.loc[1:3])

#condition 
print("\n")
print(df[df["age"]>25])

#using query()
print("\n")
print(df.query("name == 'Sayma'"))

name    Sayma
age        18
Name: 0, dtype: object


     name  age
0   Sayma   18
2  Fatima   22


     name  age
1   Arish   40
2  Fatima   22
3  ayesha   42


     name  age
1   Arish   40
3  ayesha   42


    name  age
0  Sayma   18

## set_index()
## reset_index()

In [11]:
import pandas as pd

data = {
    "name" : ["Sayma","Arish","Fatima","ayesha"],
    "age" : [18,40,22,42]
}

df = pd.DataFrame(data)
print(df)

# set_index 
df1 = df.set_index("name")
print("\n")
print(df1) # it will set name column as index 

df2 = df.set_index("name" , drop=False) # it will show "name" as index and also as a column due to "drop = False"
print("\n")
print(df2)

df3 =df.set_index("name" , inplace=True)#it changes table permanently 
print("\n")
print(df3)

print(df)

#reset_index
print("\n")
df4 = df1.reset_index() # it will return table as it is 
print(df4)

     name  age
0   Sayma   18
1   Arish   40
2  Fatima   22
3  ayesha   42


        age
name
Sayma    18
Arish    40
Fatima   22
ayesha   42


          name  age
name
Sayma    Sayma   18
Arish    Arish   40
Fatima  Fatima   22
ayesha  ayesha   42


None
        age
name
Sayma    18
Arish    40
Fatima   22
ayesha   42


     name  age
0   Sayma   18
1   Arish   40
2  Fatima   22
3  ayesha   42

# Data Cleaning

#### What are Missing Values?

Missing values are data entries where no value is stored.
In Pandas, missing values are represented as NaN (Not a Number).

🔹 isnull()

- Detects missing values in a dataset
- Returns True for missing values and False for non-missing values
- Used for identification, not removal
Use case: Finding incomplete records

🔹 notnull()

- Opposite of isnull()
- Returns True for valid data and False for missing values
- Useful for filtering valid rows

🔹 dropna()

- Removes rows or columns containing missing values
- Can drop:
-Rows with any missing values
-Columns with missing values
-Rows where all values are missing
-Risk of data loss if used without care
Use case: Removing invalid or incomplete records

🔹 fillna()

- Replaces missing values with specified values
- Can use:
-Constant values (0, "Unknown")
-Mean, median, or mode
-Forward fill or backward fill methods
- Preserves dataset size
Use case: Replacing missing salary with average salary

In [41]:
import pandas as pd 

data = {
    "Name" : ["azam","neha","ronit","ritesh","saniya",None],
    "Age" : [18,56,None,33,None,None],
    "Marks" : [88,45,None,None,67,None]
}

df = pd.DataFrame(data)
print(df)
df.isnull()
df.notnull()
df[df["Age"].notnull() & df["Marks"].notnull()]

df2 = pd.DataFrame(data)
df.dropna() #remove row which have NaN

df2.dropna(axis = 1) #remove column which have NaN 

df2.dropna(how="all") #remove row only if all value in a row are NaN

df2.dropna(subset=["Marks"]) # remove row if specific column has NaN 

# fillna()
df2.fillna("unavailable") # fill NaN place with constant 
df2.fillna(0)

     Name   Age  Marks
0    azam  18.0   88.0
1    neha  56.0   45.0
2   ronit   NaN    NaN
3  ritesh  33.0    NaN
4  saniya   NaN   67.0
5     NaN   NaN    NaN

     Name   Age  Marks
0    azam  18.0   88.0
1    neha  56.0   45.0
2   ronit   0.0    0.0
3  ritesh  33.0    0.0
4  saniya   0.0   67.0
5       0   0.0    0.0

🔹 rename()

- Changes column names without affecting data
- Can rename single or multiple columns
- Often used to standardize column names

In [ ]:
import pandas as pd 

data = {
    "Name" : ["azam","neha","ronit","ritesh","saniya",None],
    "Age" : [18,56,None,33,None,None],
    "Marks" : [88,45,None,None,67,None]
}

df = pd.DataFrame(data)
print(df)

df.rename(columns={"Marks" : "Student Marks"})#renaming single column

df.rename(columns={"Name" : "Student name","Age" : "Student Age"})

     Name   Age  Marks
0    azam  18.0   88.0
1    neha  56.0   45.0
2   ronit   NaN    NaN
3  ritesh  33.0    NaN
4  saniya   NaN   67.0
5     NaN   NaN    NaN

  Student name  Student Age  Marks
0         azam         18.0   88.0
1         neha         56.0   45.0
2        ronit          NaN    NaN
3       ritesh         33.0    NaN
4       saniya          NaN   67.0
5          NaN          NaN    NaN

🔹 duplicated()

- Identifies duplicate rows
- Marks duplicates as True
- Can check duplicates based on specific columns
- Use case: Detect repeated records

🔹 drop_duplicates()

- Removes duplicate rows
- Keeps the first occurrence by default
- Can keep last occurrence or remove all duplicates
- Use case: Removing repeated customer records

🔹 replace()

- Substitutes specific values with new values
- Can replace:
1. Single values
2. Multiple values
3. Lists or dictionaries of values
- Helps in standardizing data
- Use case: Converting "M" → "Male", "F" → "Female"

In [55]:
import pandas as pd 

data = {
    "Name" : ["neha","neha","ronit","ronit","saniya","saniya"],
    "Age" : [18,56,33,33,None,None],
    "Marks" : [88,45,45,45,67,None]
}

df = pd.DataFrame(data)
print(df)

df.duplicated()

df.duplicated(subset=["Name"]) # detect duplicate based on column

df.duplicated(keep="first") # keep first duplicate occurance

# drop duplicate

df.drop_duplicates()

df.drop_duplicates(subset=["Name"])# remove duplicate based on column

df.drop_duplicates(keep="last") # keep last duplicate record

df["Name"].replace("Saniya","sAniya")

     Name   Age  Marks
0    neha  18.0   88.0
1    neha  56.0   45.0
2   ronit  33.0   45.0
3   ronit  33.0   45.0
4  saniya   NaN   67.0
5  saniya   NaN    NaN

0      neha
1      neha
2     ronit
3     ronit
4    saniya
5    saniya
Name: Name, dtype: str

✅ sort_values()

🔹 Meaning
- Sorts data by column values.
- by default ascending 

🔹 Syntax
- df.sort_values(by="column_name")
- df.sort_values(by="column_name" , ascending = False)

✅ sort_index()

🔹 Meaning
- Sorts data by index, not by column values.

sort_values() → columns
sort_index() → index only

In [ ]:
import pandas as pd

data = {
    "name": ["Ayaan", "Sara", "Ayaan", "Zara", "Sara"],
    "department": ["IT", "HR", "IT", "HR", "IT"],
    "age": [23, 29, 23, 35, 29],
    "salary": [50000, 60000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)
print(df)

df.sort_values(by = "salary") # single column 
df.sort_values(by = ["department","salary"]) # using multiple columns 
df.sort_values(by="age" , ascending=False) # descending format

df.sort_index(ascending=False) # index wise sorting

    name department  age  salary
0  Ayaan         IT   23   50000
1   Sara         HR   29   60000
2  Ayaan         IT   23   52000
3   Zara         HR   35   58000
4   Sara         IT   29   61000

    name department  age  salary
3   Zara         HR   35   58000
4   Sara         IT   29   61000
1   Sara         HR   29   60000
0  Ayaan         IT   23   50000
2  Ayaan         IT   23   52000

🔹 FILTERING DATA

Filtering means selecting rows based on conditions.

In [11]:
import pandas as pd

data = {
    "name": ["Ayaan", "Sara", "Ayaan", "Zara", "Sara"],
    "department": ["IT", "HR", "IT", "HR", "IT"],
    "age": [23, 29, 23, 35, 29],
    "salary": [50000, 60000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)
print(df)

df[df["age"]>25]
df[df["department"]=="IT"]
df[(df["age"]>25) & (df["salary"]>55000)]

    name department  age  salary
0  Ayaan         IT   23   50000
1   Sara         HR   29   60000
2  Ayaan         IT   23   52000
3   Zara         HR   35   58000
4   Sara         IT   29   61000

   name department  age  salary
1  Sara         HR   29   60000
3  Zara         HR   35   58000
4  Sara         IT   29   61000

🔹 APPLYING FUNCTIONS

In [ ]:
import pandas as pd

data = {
    "name": ["Ayaan", "Sara", "Ayaan", "Zara", "Sara"],
    "department": ["IT", "HR", "IT", "HR", "IT"],
    "age": [23, 29, 23, 35, 29],
    "salary": [50000, 60000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)
print(df)

df["salary"] = df["salary"].apply(lambda x: x * 1.10) #Applies a function row-wise or column-wise.
print(df)

df["department"].map({"IT": "Tech", "HR": "Human Resources"}) #Used on Series only to map values.

    name department  age  salary
0  Ayaan         IT   23   50000
1   Sara         HR   29   60000
2  Ayaan         IT   23   52000
3   Zara         HR   35   58000
4   Sara         IT   29   61000
    name department  age   salary
0  Ayaan         IT   23  55000.0
1   Sara         HR   29  66000.0
2  Ayaan         IT   23  57200.0
3   Zara         HR   35  63800.0
4   Sara         IT   29  67100.0

0               Tech
1    Human Resources
2               Tech
3    Human Resources
4               Tech
Name: department, dtype: str

🔹 AGGREGATION FUNCTIONS

In [ ]:
import pandas as pd

data = {
    "name": ["Ayaan", "Sara", "Ayaan", "Zara", "Sara"],
    "department": ["IT", "HR", "IT", "HR", "IT"],
    "age": [23, 29, 23, 35, 29],
    "salary": [50000, 60000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)
print(df)

df["salary"].sum() #sum of all column 
df["age"].min() #minimum value
df["age"].max() #maximum value
df["salary"].mean() #average value

    name department  age  salary
0  Ayaan         IT   23   50000
1   Sara         HR   29   60000
2  Ayaan         IT   23   52000
3   Zara         HR   35   58000
4   Sara         IT   29   61000

np.int64(281000)

🔹 GROUPBY OPERATIONS
✅ groupby()

🔹 Meaning

Split data into groups → apply aggregation → combine result.

In [ ]:
import pandas as pd

data = {
    "name": ["Ayaan", "Sara", "Ayaan", "Zara", "Sara"],
    "department": ["IT", "HR", "IT", "HR", "IT"],
    "age": [23, 29, 23, 35, 29],
    "salary": [50000, 60000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)
print(df)

df.groupby("department")["salary"].mean() #single column ,single agg function
df.groupby("department")["age"].agg(["min","max","mean"]) #single column , multiple agg function 
df.groupby(["name","department"])["salary"].max() #multiple column , single agg function 
df.groupby(["name","department"])["age"].agg(["min","max","mean"]) # multiple column, multiple agg function

    name department  age  salary
0  Ayaan         IT   23   50000
1   Sara         HR   29   60000
2  Ayaan         IT   23   52000
3   Zara         HR   35   58000
4   Sara         IT   29   61000

                  min  max  mean
name  department
Ayaan IT           23   23  23.0
Sara  HR           29   29  29.0
      IT           29   29  29.0
Zara  HR           35   35  35.0

🔹 Working with Columns & Rows

In [50]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ayaan", "Sara", "Zara"],
    "department": ["IT", "HR", "IT"],
    "salary": [50000, 60000, 55000]
})

print(df)
print("\n")

#Adding new column
df["bonus"] = 5000 #direct assignment 
print(df)
print("\n")


df["total_salary"] = df["bonus"] + df["salary"] #calculation from columns 
print(df)
print("\n")

df["tax"] = df["total_salary"].apply(lambda x : x * 0.10) #applying functions 
print(df)
print("\n")

# droping columns 
df.drop("bonus" , axis=1 , inplace=True) #single column
print(df)
print("\n")

df.drop([0,1] ,axis=0 ,inplace=True) # droping multiple rows 
print(df)
print("\n")

df.drop(["total_salary","tax"] ,axis=1 ,inplace=True) # droping multiple rows 
print(df)
print("\n")


#Adding new row 
df.loc[0] = ["fatima","IT",80000] #adding row using loc[]
print(df)
print("\n")

#using concat()
new_row = pd.DataFrame({
    "name": ["Ali"],
    "department": ["IT"],
    "salary": [58000]
})

df = pd.concat([df, new_row], ignore_index=True)
print(df)
print("\n")

    name department  salary
0  Ayaan         IT   50000
1   Sara         HR   60000
2   Zara         IT   55000


    name department  salary  bonus
0  Ayaan         IT   50000   5000
1   Sara         HR   60000   5000
2   Zara         IT   55000   5000


    name department  salary  bonus  total_salary
0  Ayaan         IT   50000   5000         55000
1   Sara         HR   60000   5000         65000
2   Zara         IT   55000   5000         60000


    name department  salary  bonus  total_salary     tax
0  Ayaan         IT   50000   5000         55000  5500.0
1   Sara         HR   60000   5000         65000  6500.0
2   Zara         IT   55000   5000         60000  6000.0


    name department  salary  total_salary     tax
0  Ayaan         IT   50000         55000  5500.0
1   Sara         HR   60000         65000  6500.0
2   Zara         IT   55000         60000  6000.0


   name department  salary  total_salary     tax
2  Zara         IT   55000         60000  6000.0


   name department  salary
2  Zara         IT   55000


     name department  salary
2    Zara         IT   55000
0  fatima         IT   80000


     name department  salary
0    Zara         IT   55000
1  fatima         IT   80000
2     Ali         IT   58000

🔹 Combining & Merging Data

🔹 1. CONCATENATION — concat()
✅ Meaning

Stack DataFrames together (row-wise or column-wise).

📌 Think: just stick them together, no matching keys.

🔹 2. MERGING DATA — merge()
✅ Meaning

Combine DataFrames based on common column (key).

📌 SQL-style joins.

🔹 INNER JOIN
🔹 Meaning

Keep only matching rows in both DataFrames.

🔹 LEFT JOIN
🔹 Meaning

All rows from left DataFrame, match from right.

🔹 3. JOIN USING INDEX — join()
✅ Meaning

Join DataFrames using index instead of column.
- Default join = LEFT JOIN

In [ ]:
import pandas as pd

employees = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["Ayaan", "Sara", "Zara", "Ali"],
    "department": ["IT", "HR", "IT", "Finance"]
})

print(employees)

print("\n")
salaries = pd.DataFrame({
    "emp_id" : [1,2,4,5],
    "salary" : [54000,48000,90000,50000]
})
print(salaries)

#concat()
pd.concat([employees, employees]) #Row-wise concatenation (default)
pd.concat([employees, employees], ignore_index=True) #It ignore the index 
pd.concat([employees,salaries] , axis=1) #Matches by index, NOT by column values.

#merge()
pd.merge(employees,salaries,on="emp_id",how="inner") #Keep only matching rows in both DataFrames.
pd.merge(employees,salaries,on="emp_id",how="left") #All rows from left DataFrame, match from right.
pd.merge(employees,salaries,on="emp_id",how="right") #All rows from right DataFrame, match from left.
pd.merge(employees,salaries,on="emp_id",how="outer") #Keep all rows from both DataFrames

#JOIN USING INDEX — join()
employees_indexed = employees.set_index("emp_id")
salaries_indexed = salaries.set_index("emp_id")

employees_indexed.join(salaries_indexed) #outer join
employees_indexed.join(salaries_indexed, how="inner") #inner join

   emp_id   name department
0       1  Ayaan         IT
1       2   Sara         HR
2       3   Zara         IT
3       4    Ali    Finance


   emp_id  salary
0       1   54000
1       2   48000
2       4   90000
3       5   50000

         name department  salary
emp_id
1       Ayaan         IT   54000
2        Sara         HR   48000
4         Ali    Finance   90000

🔹 1. DATETIME BASICS
✅ Why DateTime matters

Raw dates are usually strings, Pandas can’t extract year/month until you convert them.

✅ Convert to datetime — to_datetime()
🔹 Meaning

Converts string → datetime object.

🔹 2. DATE EXTRACTION (.dt accessor)

- Attribute	    Meaning

- year	    =    Extract year
- month	    =    Extract month
- day	     =   Extract day
- day_name()  = 	Monday, Tuesday…

In [35]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ayaan Khan", "Sara Ali", "Zara Sheikh"],
    "join_date": ["2023-05-10", "2022-12-01", "2024-01-15"],
    "email": ["Ayaan@Gmail.com", "sara_ali@yahoo.com", "zara.sheikh@outlook.com"]
})

print(df)
print("\n")

#convert to datetime 
print(df.dtypes)
print("\n")

df["join_date"] = pd.to_datetime(df["join_date"])
print(df.dtypes)
print("\n")

#date extraction
df["year"] = df["join_date"].dt.year
print(df)
print("\n")

df["month"] = df["join_date"].dt.month
print(df)
print("\n")

df["date"] = df["join_date"].dt.day
print(df)
print("\n")

df["day"] = df["join_date"].dt.day_name()
print(df)
print("\n")

#string operation 
df["lower_case"] = df["email"].str.lower()
print(df)
print("\n")

df["upper_case"] = df["name"].str.upper()
print(df)
print("\n")

df["first_name"] = df["name"].str.split(" ").str[0]
print(df)
print("\n")

          name   join_date                    email
0   Ayaan Khan  2023-05-10          Ayaan@Gmail.com
1     Sara Ali  2022-12-01       sara_ali@yahoo.com
2  Zara Sheikh  2024-01-15  zara.sheikh@outlook.com


name         str
join_date    str
email        str
dtype: object


name                    str
join_date    datetime64[us]
email                   str
dtype: object


          name  join_date                    email  year
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024


          name  join_date                    email  year  month
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1


          name  join_date                    email  year  month  date
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5    10
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12     1
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1    15


          name  join_date                    email  year  month  date  \
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5    10
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12     1
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1    15

         day
0  Wednesday
1   Thursday
2     Monday


          name  join_date                    email  year  month  date  \
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5    10
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12     1
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1    15

         day               lower_case
0  Wednesday          ayaan@gmail.com
1   Thursday       sara_ali@yahoo.com
2     Monday  zara.sheikh@outlook.com


          name  join_date                    email  year  month  date  \
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5    10
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12     1
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1    15

         day               lower_case   upper_case
0  Wednesday          ayaan@gmail.com   AYAAN KHAN
1   Thursday       sara_ali@yahoo.com     SARA ALI
2     Monday  zara.sheikh@outlook.com  ZARA SHEIKH


          name  join_date                    email  year  month  date  \
0   Ayaan Khan 2023-05-10          Ayaan@Gmail.com  2023      5    10
1     Sara Ali 2022-12-01       sara_ali@yahoo.com  2022     12     1
2  Zara Sheikh 2024-01-15  zara.sheikh@outlook.com  2024      1    15

         day               lower_case   upper_case first_name
0  Wednesday          ayaan@gmail.com   AYAAN KHAN      Ayaan
1   Thursday       sara_ali@yahoo.com     SARA ALI       Sara
2     Monday  zara.sheikh@outlook.com  ZARA SHEIKH       Zara

FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'